#!/usr/bin/env python

import sys

from irc.bot import SingleServerIRCBot


class IRCBot(SingleServerIRCBot):

    def __init__(self, channel, nickname, server, server_password, port=6667):
        super(IRCBot, self).__init__([(server, port, server_password)], nickname, nickname)
        self.channel = channel

    def on_nicknameinuse(self, connection, event):
        connection.nick(connection.get_nickname() + "_")

    def on_welcome(self, connection, event):
        connection.join(self.channel)

    def on_pubmsg(self, connection, event):
        channel = self.channels[self.channel]
        users_from_channel = channel.users()
        connection.privmsg(self.channel, '%s disse: %s %s' % (
            event.source.nick,
            ' '.join(users_from_channel),
            event.arguments[0])
        )


def main():
    if len(sys.argv) < 4 or len(sys.argv) > 5:
        print("Usage: ./bot <server[:port]> <channel> <nickname> [server_password]")
        sys.exit(1)

    server_and_port = sys.argv[1].split(":", 1)
    server = server_and_port[0]

    if len(server_and_port) == 2:
        try:
            port = int(server_and_port[1])
        except ValueError:
            print("Error: Erroneous port.")
            sys.exit(1)
    else:
        port = 6667

    channel = sys.argv[2]
    nickname = sys.argv[3]

    try:
        server_password = sys.argv[4]
    except IndexError:
        server_password = None

    bot = IRCBot(channel, nickname, server, server_password, port)
    bot.start()

if __name__ == "__main__":
    main()
